# coding: utf-8

"""
    Multilogin X Launcher API

    Launcher API is used to work with profiles in the browser (start, stop, get statuses).

    The version of the OpenAPI document: 1.0.0
    Contact: support@multilogin.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class ProfileExportStatus(BaseModel):
    """
    ProfileExportStatus
    """ # noqa: E501
    export_id: StrictStr = Field(description="A unique identifier for the export process. This ID is used to track the status and details of the export. The export ID is typically generated at the start of the export process. ")
    profile_id: StrictStr = Field(description="the unique identifier for the profile related to this export")
    status: StrictStr = Field(description="The current status of the export process. Possible values include: - \"running\": The export process is currently in progress. - \"done\": The export process has completed successfully. - \"failed\": The export process encountered an error and did not complete successfully. ")
    timestamp: StrictInt = Field(description="The timestamp indicating when the status of the export process was last updated. This field helps in tracking the exact time of status changes. ")
    message: StrictStr = Field(description="Providing additional information about the export process. If the status is \"failed\", this field contains details about the error encountered. ")
    export_path: StrictStr = Field(description="The location or path where the exported profile is saved or stored")
    __properties: ClassVar[List[str]] = ["export_id", "profile_id", "status", "timestamp", "message", "export_path"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['running', 'done', 'failed']):
            raise ValueError("must be one of enum values ('running', 'done', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProfileExportStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProfileExportStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "export_id": obj.get("export_id"),
            "profile_id": obj.get("profile_id"),
            "status": obj.get("status"),
            "timestamp": obj.get("timestamp"),
            "message": obj.get("message"),
            "export_path": obj.get("export_path")
        })
        return _obj


